-- NEXUS AI DataOps — Warehouses
-- Executar como SYSADMIN

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NEXUS_UI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Streamlit UI e queries leves de usuário';

CREATE WAREHOUSE IF NOT EXISTS NEXUS_COMPUTE_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Cortex Agents, Cortex Analyst, queries de marts';

CREATE WAREHOUSE IF NOT EXISTS NEXUS_ML_WH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Treino e inference de modelos Snowpark ML';

CREATE WAREHOUSE IF NOT EXISTS NEXUS_ORCHESTRATION_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Tasks de orquestração: audit log, data quality, embeddings, briefing';

CREATE WAREHOUSE IF NOT EXISTS NEXUS_INGEST_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Pipelines de ingestão: COPY INTO, dbt run, embedding pipeline';
