-- NEXUS AI DataOps — RBAC
-- Executar como SECURITYADMIN

USE ROLE SECURITYADMIN;

-- Roles funcionais do produto
CREATE ROLE IF NOT EXISTS NEXUS_ADMIN
    COMMENT = 'Administrador do NEXUS: acesso total, sem masking de PII';

CREATE ROLE IF NOT EXISTS NEXUS_ANALYST
    COMMENT = 'Analista: acesso a marts e agentes, PII mascarado';

CREATE ROLE IF NOT EXISTS NEXUS_VIEWER
    COMMENT = 'Visualizador: dashboards e chat, sem dados brutos';

CREATE ROLE IF NOT EXISTS NEXUS_DATA_ENGINEER
    COMMENT = 'Engenheiro de dados: acesso a RAW, STD, pipelines, quality';

-- Hierarquia de roles
GRANT ROLE NEXUS_VIEWER    TO ROLE NEXUS_ANALYST;
GRANT ROLE NEXUS_ANALYST   TO ROLE NEXUS_ADMIN;
GRANT ROLE NEXUS_ADMIN     TO ROLE SYSADMIN;

-- Grants de warehouse por role
USE ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE NEXUS_UI_WH          TO ROLE NEXUS_VIEWER;
GRANT USAGE ON WAREHOUSE NEXUS_COMPUTE_WH     TO ROLE NEXUS_ANALYST;
GRANT USAGE ON WAREHOUSE NEXUS_INGEST_WH      TO ROLE NEXUS_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE NEXUS_ML_WH          TO ROLE NEXUS_ADMIN;
GRANT USAGE ON WAREHOUSE NEXUS_ORCHESTRATION_WH TO ROLE NEXUS_DATA_ENGINEER;

-- Grants de database
GRANT USAGE ON DATABASE NEXUS_APP TO ROLE NEXUS_VIEWER;

-- Grants por schema (VIEWER: apenas MART, AI, CONFIG)
GRANT USAGE ON SCHEMA NEXUS_APP.MART       TO ROLE NEXUS_VIEWER;
GRANT USAGE ON SCHEMA NEXUS_APP.AI         TO ROLE NEXUS_VIEWER;
GRANT USAGE ON SCHEMA NEXUS_APP.CONFIG     TO ROLE NEXUS_VIEWER;

-- ANALYST: adiciona CORE e AUDIT (leitura)
GRANT USAGE ON SCHEMA NEXUS_APP.CORE       TO ROLE NEXUS_ANALYST;
GRANT USAGE ON SCHEMA NEXUS_APP.AUDIT      TO ROLE NEXUS_ANALYST;
GRANT USAGE ON SCHEMA NEXUS_APP.GOVERNANCE TO ROLE NEXUS_ANALYST;

-- DATA_ENGINEER: adiciona RAW e STD
GRANT USAGE ON SCHEMA NEXUS_APP.RAW        TO ROLE NEXUS_DATA_ENGINEER;
GRANT USAGE ON SCHEMA NEXUS_APP.STD        TO ROLE NEXUS_DATA_ENGINEER;

-- ADMIN: acesso total
GRANT ALL ON DATABASE NEXUS_APP            TO ROLE NEXUS_ADMIN;

-- Future grants automáticos
USE ROLE SYSADMIN;

GRANT SELECT ON FUTURE TABLES IN SCHEMA NEXUS_APP.MART       TO ROLE NEXUS_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NEXUS_APP.AI         TO ROLE NEXUS_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NEXUS_APP.CORE       TO ROLE NEXUS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NEXUS_APP.AUDIT      TO ROLE NEXUS_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NEXUS_APP.GOVERNANCE TO ROLE NEXUS_ANALYST;
GRANT ALL     ON FUTURE TABLES IN SCHEMA NEXUS_APP.RAW       TO ROLE NEXUS_DATA_ENGINEER;
GRANT ALL     ON FUTURE TABLES IN SCHEMA NEXUS_APP.STD       TO ROLE NEXUS_DATA_ENGINEER;
GRANT ALL     ON FUTURE DYNAMIC TABLES IN SCHEMA NEXUS_APP.MART TO ROLE NEXUS_ANALYST;
GRANT ALL     ON FUTURE DYNAMIC TABLES IN SCHEMA NEXUS_APP.AI   TO ROLE NEXUS_ANALYST;

-- Tabela de mapeamento role → agente (usada pela UI)
USE ROLE NEXUS_ADMIN;
USE DATABASE NEXUS_APP;

CREATE TABLE IF NOT EXISTS NEXUS_APP.CONFIG.ROLE_AGENT_MAP (
    role_name       VARCHAR(255) NOT NULL,
    agent_id        VARCHAR(100) NOT NULL,
    vertical_pack   VARCHAR(100) NOT NULL DEFAULT 'saas_customer',
    created_at      TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (role_name, vertical_pack)
);

MERGE INTO NEXUS_APP.CONFIG.ROLE_AGENT_MAP AS tgt
USING (
    SELECT 'NEXUS_ADMIN'         AS role_name, 'executive_agent'   AS agent_name, 'saas_customer' AS vertical_pack, CURRENT_TIMESTAMP() AS assigned_at
    UNION ALL SELECT 'NEXUS_ANALYST',       'revenue_agent',    'saas_customer', CURRENT_TIMESTAMP()
    UNION ALL SELECT 'NEXUS_VIEWER',        'customer_agent',   'saas_customer', CURRENT_TIMESTAMP()
    UNION ALL SELECT 'NEXUS_DATA_ENGINEER', 'data_steward_agent','saas_customer', CURRENT_TIMESTAMP()
) AS src ON tgt.role_name = src.role_name AND tgt.vertical_pack = src.vertical_pack
WHEN NOT MATCHED THEN INSERT (role_name, agent_name, vertical_pack, assigned_at)
    VALUES (src.role_name, src.agent_name, src.vertical_pack, src.assigned_at);

-- Mapeamento usuário → org_id (usado pela Row Access Policy de isolamento multi-tenant)
CREATE TABLE IF NOT EXISTS NEXUS_APP.CONFIG.ORG_USER_MAP (
    org_id      VARCHAR(36)  NOT NULL,
    user_name   VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (org_id, user_name)
);
