-- NEXUS AI DataOps — Masking Policies (PII)
-- NEXUS_ADMIN vê dados reais; demais roles recebem valores mascarados

USE ROLE SECURITYADMIN;
USE DATABASE NEXUS_APP;

CREATE MASKING POLICY IF NOT EXISTS NEXUS_APP.GOVERNANCE.MASK_EMAIL
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NEXUS_ADMIN', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE REGEXP_REPLACE(val, '(^[^@]{1,2})[^@]*(@.*)', '\\1***\\2')
    END
COMMENT = 'Mascara email: j***@example.com para non-admin';

CREATE MASKING POLICY IF NOT EXISTS NEXUS_APP.GOVERNANCE.MASK_PHONE
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NEXUS_ADMIN', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE REGEXP_REPLACE(val, '(\\d{2})(\\d+)(\\d{2})', '\\1****\\3')
    END
COMMENT = 'Mascara telefone: mantém primeiros e últimos 2 dígitos';

CREATE MASKING POLICY IF NOT EXISTS NEXUS_APP.GOVERNANCE.MASK_NAME
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NEXUS_ADMIN', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE SPLIT_PART(val, ' ', 1) || ' ****'
    END
COMMENT = 'Mascara sobrenome: mantém apenas primeiro nome';

CREATE MASKING POLICY IF NOT EXISTS NEXUS_APP.GOVERNANCE.MASK_TEXT_PII
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('NEXUS_ADMIN', 'SYSADMIN', 'ACCOUNTADMIN') THEN val
        WHEN val IS NULL THEN NULL
        ELSE '[CONTEÚDO MASCARADO — APENAS NEXUS_ADMIN]'
    END
COMMENT = 'Mascara campos de texto com possível PII (prompts, descrições)';

-- Aplicar nas colunas PII de CORE.CUSTOMERS
ALTER TABLE NEXUS_APP.CORE.CUSTOMERS
    MODIFY COLUMN email  SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_EMAIL FORCE;

ALTER TABLE NEXUS_APP.CORE.CUSTOMERS
    MODIFY COLUMN phone  SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_PHONE FORCE;

ALTER TABLE NEXUS_APP.CORE.CUSTOMERS
    MODIFY COLUMN name   SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_NAME FORCE;

-- Aplicar em AUDIT.PROMPT_LOG (prompts podem conter PII)
ALTER TABLE NEXUS_APP.AUDIT.PROMPT_LOG
    MODIFY COLUMN user_name   SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_NAME FORCE;

ALTER TABLE NEXUS_APP.AUDIT.PROMPT_LOG
    MODIFY COLUMN prompt_text SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_TEXT_PII FORCE;

-- Aplicar em CORE.INTERACTIONS (corpo de mensagens)
ALTER TABLE NEXUS_APP.CORE.INTERACTIONS
    MODIFY COLUMN body_summary SET MASKING POLICY NEXUS_APP.GOVERNANCE.MASK_TEXT_PII FORCE;
