-- NEXUS AI DataOps — Row Access Policies (isolamento multi-tenant)
-- Garante que cada org_id veja apenas seus próprios dados

USE ROLE SECURITYADMIN;
USE DATABASE NEXUS_APP;

-- Tabela de mapeamento: usuário Snowflake → org_id
USE ROLE NEXUS_ADMIN;

CREATE TABLE IF NOT EXISTS NEXUS_APP.CONFIG.USER_ORG_MAP (
    user_name   VARCHAR(255)    NOT NULL,
    org_id      VARCHAR(36)     NOT NULL,
    created_at  TIMESTAMP_TZ    NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (user_name, org_id)
);

-- Policy: usuário vê apenas dados da sua org (ADMIN vê tudo)
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION
AS (org_id VARCHAR) RETURNS BOOLEAN ->
    CURRENT_ROLE() IN ('NEXUS_ADMIN', 'SYSADMIN', 'ACCOUNTADMIN')
    OR EXISTS (
        SELECT 1
        FROM NEXUS_APP.CONFIG.USER_ORG_MAP m
        WHERE m.user_name = CURRENT_USER()
          AND m.org_id = org_id
    )
COMMENT = 'Isola dados por org_id — multi-tenant isolation';

-- Aplicar em todas as tabelas com org_id
ALTER TABLE NEXUS_APP.CORE.CUSTOMERS     ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.CORE.TRANSACTIONS  ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.CORE.TICKETS       ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.CORE.CONTRACTS     ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.CORE.DOCUMENTS     ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.CORE.INTERACTIONS  ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.AI.CHURN_SCORES    ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.AI.RECOMMENDATIONS ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.AUDIT.PROMPT_LOG   ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.AUDIT.ACCESS_LOG   ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
ALTER TABLE NEXUS_APP.AUDIT.ACTION_LOG   ADD ROW ACCESS POLICY NEXUS_APP.GOVERNANCE.ORG_ISOLATION ON (org_id);
