-- NEXUS AI DataOps — Roles por agente (RBAC granular)
-- Sprint 2 — P1: cada Cortex Agent tem um application role com acesso mínimo

USE DATABASE NEXUS_APP;

-- ─────────────────────────────────────────────────────────────────────────────
-- Application Roles por agente
-- ─────────────────────────────────────────────────────────────────────────────

CREATE ROLE IF NOT EXISTS AGENT_EXECUTIVE_READONLY;
CREATE ROLE IF NOT EXISTS AGENT_REVENUE_READONLY;
CREATE ROLE IF NOT EXISTS AGENT_CUSTOMER_READONLY;
CREATE ROLE IF NOT EXISTS AGENT_RISK_READONLY;
CREATE ROLE IF NOT EXISTS AGENT_DATA_STEWARD_READONLY;
CREATE ROLE IF NOT EXISTS AGENT_OPERATIONS_READONLY;

-- Hierarquia: NEXUS_ANALYST herda todos os agent roles de leitura
GRANT ROLE AGENT_EXECUTIVE_READONLY   TO ROLE NEXUS_ANALYST;
GRANT ROLE AGENT_REVENUE_READONLY     TO ROLE NEXUS_ANALYST;
GRANT ROLE AGENT_CUSTOMER_READONLY    TO ROLE NEXUS_ANALYST;
GRANT ROLE AGENT_RISK_READONLY        TO ROLE NEXUS_ANALYST;
GRANT ROLE AGENT_DATA_STEWARD_READONLY TO ROLE NEXUS_ANALYST;
GRANT ROLE AGENT_OPERATIONS_READONLY  TO ROLE NEXUS_ANALYST;

-- ─────────────────────────────────────────────────────────────────────────────
-- GRANTs por agente — princípio de least privilege
-- ─────────────────────────────────────────────────────────────────────────────

-- Executive Agent — KPIs, briefings, DTs executivos
GRANT SELECT ON DYNAMIC TABLE MART.DT_EXECUTIVE_KPIS        TO ROLE AGENT_EXECUTIVE_READONLY;
GRANT SELECT ON TABLE         AI.EXECUTIVE_BRIEFINGS         TO ROLE AGENT_EXECUTIVE_READONLY;
GRANT SELECT ON TABLE         CONFIG.APP_SETTINGS            TO ROLE AGENT_EXECUTIVE_READONLY;

-- Revenue Agent — transações, revenue movement, opportunity score
GRANT SELECT ON DYNAMIC TABLE MART.DT_REVENUE_MOVEMENT           TO ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON DYNAMIC TABLE MART.DT_REVENUE_OPPORTUNITY_SCORE  TO ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.TRANSACTIONS                   TO ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.SUBSCRIPTIONS                  TO ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.PRODUCTS                       TO ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         MART.REVENUE_OPPORTUNITY_SCORE      TO ROLE AGENT_REVENUE_READONLY;

-- Customer Agent — 360 view, churn, tickets, interactions
GRANT SELECT ON DYNAMIC TABLE MART.DT_CUSTOMER_HEALTH      TO ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         CORE.CUSTOMERS               TO ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         CORE.INTERACTIONS            TO ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         AI.CHURN_SCORES              TO ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         AI.RECOMMENDATIONS           TO ROLE AGENT_CUSTOMER_READONLY;

-- Risk Agent — alertas, anomalias, audit
GRANT SELECT ON TABLE AUDIT.ACTION_LOG                     TO ROLE AGENT_RISK_READONLY;
GRANT SELECT ON TABLE AUDIT.PROMPT_LOG                     TO ROLE AGENT_RISK_READONLY;
GRANT SELECT ON TABLE AUDIT.DATA_QUALITY_RESULTS           TO ROLE AGENT_RISK_READONLY;

-- Data Steward Agent — governança, PII, qualidade
GRANT SELECT ON VIEW  GOVERNANCE.V_PII_INVENTORY           TO ROLE AGENT_DATA_STEWARD_READONLY;
GRANT SELECT ON TABLE AUDIT.DATA_QUALITY_RESULTS           TO ROLE AGENT_DATA_STEWARD_READONLY;
GRANT SELECT ON TABLE CONFIG.APP_SETTINGS                  TO ROLE AGENT_DATA_STEWARD_READONLY;

-- Operations Agent (6º agente) — tickets, SLA, health, interactions
GRANT SELECT ON TABLE         CORE.TICKETS                 TO ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         CORE.INTERACTIONS            TO ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON DYNAMIC TABLE MART.DT_CUSTOMER_HEALTH     TO ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         AUDIT.ACTION_LOG             TO ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         CORE.ACCOUNTS                TO ROLE AGENT_OPERATIONS_READONLY;

-- KBS — todos os agents podem consultar o Knowledge Base
GRANT USAGE  ON SCHEMA         KBS                         TO ROLE NEXUS_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA KBS                   TO ROLE NEXUS_VIEWER;
GRANT USAGE  ON CORTEX SEARCH SERVICE KBS.KB_SEARCH_SERVICE TO ROLE NEXUS_VIEWER;
