-- NEXUS AI DataOps — Roles por agente (RBAC granular)
-- Sprint 2 — P1: cada Cortex Agent tem um application role com acesso mínimo

USE DATABASE NEXUS_APP;

-- ─────────────────────────────────────────────────────────────────────────────
-- Application Roles por agente
-- ─────────────────────────────────────────────────────────────────────────────

CREATE APPLICATION ROLE IF NOT EXISTS AGENT_EXECUTIVE_READONLY;
CREATE APPLICATION ROLE IF NOT EXISTS AGENT_REVENUE_READONLY;
CREATE APPLICATION ROLE IF NOT EXISTS AGENT_CUSTOMER_READONLY;
CREATE APPLICATION ROLE IF NOT EXISTS AGENT_RISK_READONLY;
CREATE APPLICATION ROLE IF NOT EXISTS AGENT_DATA_STEWARD_READONLY;
CREATE APPLICATION ROLE IF NOT EXISTS AGENT_OPERATIONS_READONLY;

-- Hierarquia: NEXUS_ANALYST herda todos os agent roles de leitura
GRANT APPLICATION ROLE AGENT_EXECUTIVE_READONLY   TO APPLICATION ROLE NEXUS_ANALYST;
GRANT APPLICATION ROLE AGENT_REVENUE_READONLY     TO APPLICATION ROLE NEXUS_ANALYST;
GRANT APPLICATION ROLE AGENT_CUSTOMER_READONLY    TO APPLICATION ROLE NEXUS_ANALYST;
GRANT APPLICATION ROLE AGENT_RISK_READONLY        TO APPLICATION ROLE NEXUS_ANALYST;
GRANT APPLICATION ROLE AGENT_DATA_STEWARD_READONLY TO APPLICATION ROLE NEXUS_ANALYST;
GRANT APPLICATION ROLE AGENT_OPERATIONS_READONLY  TO APPLICATION ROLE NEXUS_ANALYST;

-- ─────────────────────────────────────────────────────────────────────────────
-- GRANTs por agente — princípio de least privilege
-- ─────────────────────────────────────────────────────────────────────────────

-- Executive Agent — KPIs, briefings, DTs executivos
GRANT SELECT ON DYNAMIC TABLE MART.DT_EXECUTIVE_KPIS        TO APPLICATION ROLE AGENT_EXECUTIVE_READONLY;
GRANT SELECT ON TABLE         AI.EXECUTIVE_BRIEFINGS         TO APPLICATION ROLE AGENT_EXECUTIVE_READONLY;
GRANT SELECT ON TABLE         CONFIG.APP_SETTINGS            TO APPLICATION ROLE AGENT_EXECUTIVE_READONLY;

-- Revenue Agent — transações, revenue movement, opportunity score
GRANT SELECT ON DYNAMIC TABLE MART.DT_REVENUE_MOVEMENT           TO APPLICATION ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON DYNAMIC TABLE MART.DT_REVENUE_OPPORTUNITY_SCORE  TO APPLICATION ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.TRANSACTIONS                   TO APPLICATION ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.SUBSCRIPTIONS                  TO APPLICATION ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         CORE.PRODUCTS                       TO APPLICATION ROLE AGENT_REVENUE_READONLY;
GRANT SELECT ON TABLE         MART.REVENUE_OPPORTUNITY_SCORE      TO APPLICATION ROLE AGENT_REVENUE_READONLY;

-- Customer Agent — 360 view, churn, tickets, interactions
GRANT SELECT ON DYNAMIC TABLE MART.DT_CUSTOMER_HEALTH      TO APPLICATION ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         CORE.CUSTOMERS               TO APPLICATION ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         CORE.INTERACTIONS            TO APPLICATION ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         AI.CHURN_SCORES              TO APPLICATION ROLE AGENT_CUSTOMER_READONLY;
GRANT SELECT ON TABLE         AI.RECOMMENDATIONS           TO APPLICATION ROLE AGENT_CUSTOMER_READONLY;

-- Risk Agent — alertas, anomalias, audit
GRANT SELECT ON TABLE AUDIT.ACTION_LOG                     TO APPLICATION ROLE AGENT_RISK_READONLY;
GRANT SELECT ON TABLE AUDIT.PROMPT_LOG                     TO APPLICATION ROLE AGENT_RISK_READONLY;
GRANT SELECT ON TABLE AUDIT.DATA_QUALITY_RESULTS           TO APPLICATION ROLE AGENT_RISK_READONLY;

-- Data Steward Agent — governança, PII, qualidade
GRANT SELECT ON VIEW  GOVERNANCE.V_PII_INVENTORY           TO APPLICATION ROLE AGENT_DATA_STEWARD_READONLY;
GRANT SELECT ON TABLE AUDIT.DATA_QUALITY_RESULTS           TO APPLICATION ROLE AGENT_DATA_STEWARD_READONLY;
GRANT SELECT ON TABLE CONFIG.APP_SETTINGS                  TO APPLICATION ROLE AGENT_DATA_STEWARD_READONLY;

-- Operations Agent (6º agente) — tickets, SLA, health, interactions
GRANT SELECT ON TABLE         CORE.TICKETS                 TO APPLICATION ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         CORE.INTERACTIONS            TO APPLICATION ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON DYNAMIC TABLE MART.DT_CUSTOMER_HEALTH     TO APPLICATION ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         AUDIT.ACTION_LOG             TO APPLICATION ROLE AGENT_OPERATIONS_READONLY;
GRANT SELECT ON TABLE         CORE.ACCOUNTS                TO APPLICATION ROLE AGENT_OPERATIONS_READONLY;

-- KBS — todos os agents podem consultar o Knowledge Base
GRANT USAGE  ON SCHEMA         KBS                         TO APPLICATION ROLE NEXUS_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA KBS                   TO APPLICATION ROLE NEXUS_VIEWER;
GRANT USAGE  ON CORTEX SEARCH SERVICE KBS.KB_SEARCH_SERVICE TO APPLICATION ROLE NEXUS_VIEWER;
